version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root@127.0.0.1:3306/jwt_auth
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=jwt_auth
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=