controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login
    methods: [POST]

api_register:
    path: /api/register
    methods: [POST]
    controller: App\Controller\RegistrationController::index

api_get_user_info:
    path: /api/user
    methods: [GET]
    controller: App\Controller\UserController::getUserInfo

api_edit_user_info:
    path: /api/user
    methods: [PUT]
    controller: App\Controller\UserController::editUserInfo

api_dashboard:
    path: /api/dashboard
    controller: App\Controller\DashboardController::index